spring:
  datasource:
    url: jdbc:mysql://localhost:5432/portal?useSSL=false
    username: postgres
    password: test1
    hikari:
      schema: portal1
custom:
  config: 
    prop1: test1
    prop2: test2
    prop3: test3
